#pragma once

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctime>
#include <cmath>
#include <time.h>
#include <string>
#include <set>
#include <vector>
#include <list>
#include <vector>
#include <algorithm>
#include <iostream>
#include <sstream>
#include <fstream>
#include <map>
#include <windows.h>
#include <dirent.h>
#include <tuple>
#include <locale>
#include <numeric>
#include <time.h>
#include <iterator>
#include <numeric>